// <auto-generated />
using System;
using ApplyFlow.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplyFlow.Api.Migrations
{
    [DbContext(typeof(ApplyFlowDbContext))]
    partial class ApplyFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplyFlow.Api.Models.ApplicationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("ApplicationEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateOnly(2026, 5, 28),
                            EventType = 0,
                            JobApplicationId = 1,
                            Note = "Application sent"
                        },
                        new
                        {
                            Id = 2,
                            EventDate = new DateOnly(2026, 6, 12),
                            EventType = 2,
                            JobApplicationId = 1,
                            Note = "Interview scheduled"
                        },
                        new
                        {
                            Id = 3,
                            EventDate = new DateOnly(2026, 6, 1),
                            EventType = 0,
                            JobApplicationId = 2,
                            Note = "Application sent with motivation letter"
                        });
                });

            modelBuilder.Entity("ApplyFlow.Api.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Bratislava",
                            Name = "SEN Systems",
                            Note = "Potential React + .NET opportunity",
                            Website = "https://www.sensystems.sk"
                        },
                        new
                        {
                            Id = 2,
                            City = "Bratislava",
                            Name = "Alanata",
                            Note = "Junior Java Developer opportunity",
                            Website = "https://www.alanata.sk"
                        });
                });

            modelBuilder.Entity("ApplyFlow.Api.Models.ContactPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("ContactPersons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Email = "hr@sensystems.sk",
                            Name = "HR Contact",
                            Note = "Interview coordination",
                            Role = "Recruiter"
                        });
                });

            modelBuilder.Entity("ApplyFlow.Api.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AppliedDate")
                        .HasColumnType("date");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SalaryMax")
                        .HasColumnType("int");

                    b.Property<int?>("SalaryMin")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WorkMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobApplications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliedDate = new DateOnly(2026, 5, 28),
                            CompanyId = 1,
                            Location = "Bratislava",
                            Note = "Minimal React knowledge required",
                            PositionTitle = "Fullstack Developer",
                            SalaryMax = 1400,
                            SalaryMin = 1200,
                            Source = 0,
                            Status = 2,
                            WorkMode = 1
                        },
                        new
                        {
                            Id = 2,
                            AppliedDate = new DateOnly(2026, 6, 1),
                            CompanyId = 2,
                            Location = "Bratislava",
                            Note = "Good match for Spring Boot practice",
                            PositionTitle = "Junior Java Developer",
                            SalaryMax = 1500,
                            SalaryMin = 1200,
                            Source = 0,
                            Status = 1,
                            WorkMode = 1
                        });
                });

            modelBuilder.Entity("ApplyFlow.Api.Models.ApplicationEvent", b =>
                {
                    b.HasOne("ApplyFlow.Api.Models.JobApplication", "JobApplication")
                        .WithMany("Events")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("ApplyFlow.Api.Models.ContactPerson", b =>
                {
                    b.HasOne("ApplyFlow.Api.Models.Company", "Company")
                        .WithMany("ContactPersons")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ApplyFlow.Api.Models.JobApplication", b =>
                {
                    b.HasOne("ApplyFlow.Api.Models.Company", "Company")
                        .WithMany("JobApplications")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ApplyFlow.Api.Models.Company", b =>
                {
                    b.Navigation("ContactPersons");

                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("ApplyFlow.Api.Models.JobApplication", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
