services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: applyflow-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_Strong_Password123!"
    ports:
      - "14333:1433"
    volumes:
      - applyflow_sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: applyflow-api
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ApplyFlowDb;User Id=sa;Password=Your_Strong_Password123!;TrustServerCertificate=True;"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./applyflow-web
      dockerfile: Dockerfile
    container_name: applyflow-web
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  applyflow_sql_data: